name: JMH Benchmark

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: <your-gcp-project-id>
        export_default_credentials: true

    - name: Run JMH Benchmark on GCP
      run: |
        gcloud builds submit --config cloudbuild.yaml --substitutions=BRANCH_NAME=${{ github.head_ref }},SHORT_SHA=${{ github.sha }} .

