name: Comment test

on:
  pull_request:


jobs:
  comment:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

    - name: Copy exported text file from Google Cloud Compute Engine
      run: |
        gcloud compute scp root@instance-1:main/NullAway/jmh/build/results/jmh/results.txt ./exported_text.txt --zone us-central1-a
        
    - name: Identifier
      run:  |
        (echo '```Main Benchmark:
        ' ; cat exported_text.txt; echo '```') > main.txt
   
    - name: Comment 2
      uses: mshick/add-pr-comment@v2
      if: always()
      with:         
        message-path: main.txt     
