name: JMH Benchmark

on:
  issue_comment:
    types: [created]


jobs:
  setup:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/benchmark')
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set branch name
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=${{ github.event.issue.number }}
        PR_DETAILS=$(curl -s -H "Authorization: token $GH_TOKEN" "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")
        REPO_NAME=$(echo "$PR_DETAILS" | jq -r .head.repo.full_name)
        BRANCH_NAME=$(echo "$PR_DETAILS" | jq -r .head.ref)
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
    
    - id: 'auth'
      name: Authenticating
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
      
    - name: Setup Directory and Copy Bash Scripts
      run: | 
        chmod +x ./.github/workflows/gcloud_ssh.sh
        ./.github/workflows/gcloud_ssh.sh "export BRANCH_NAME=${BRANCH_NAME} && mkdir $BRANCH_NAME"
        gcloud compute scp ./.github/workflows/run_pr_benchmarks.sh root@instance-1:$BRANCH_NAME/ --zone=us-central1-a
        gcloud compute scp ./.github/workflows/run_main_benchmarks.sh root@instance-1:$BRANCH_NAME/ --zone=us-central1-a

    - name: Run JMH benchmarks for PR Branch
      run: |
        chmod +x ./.github/workflows/gcloud_ssh.sh
        ./.github/workflows/gcloud_ssh.sh " export BRANCH_NAME=${BRANCH_NAME} && export REPO_NAME=${REPO_NAME} && chmod +x $BRANCH_NAME/run_pr_benchmarks.sh && $BRANCH_NAME/run_pr_benchmarks.sh"
          
    - name: Copy exported PR benchmark file from Google Cloud Compute Engine
      run: |
        gcloud compute scp root@instance-1:$BRANCH_NAME/pr/NullAway/jmh/build/results/jmh/results.txt ./pr_text.txt --zone us-central1-a
    
    
    - name: Run JMH benchmarks for Main Branch
      run: |
        ./.github/workflows/gcloud_ssh.sh " export BRANCH_NAME=${BRANCH_NAME} && chmod +x $BRANCH_NAME/run_main_benchmarks.sh && $BRANCH_NAME/run_main_benchmarks.sh "
          
    - name: Copy exported Main Benchmark file from Google Cloud Compute Engine 
      run: |
        gcloud compute scp root@instance-1:$BRANCH_NAME/main/NullAway/jmh/build/results/jmh/results.txt ./main_text.txt --zone us-central1-a
        
    - name: Formatting Benchmark
      run:  |
        (echo 'Main Benchmark:'; echo '```' ; cat main_text.txt; echo '```'; echo 'PR Benchmark:'; echo '```' ; cat pr_text.txt; echo '```') > benchmark.txt
   
    - name: Comment Benchmark
      uses: mshick/add-pr-comment@v2
      if: always()
      with:         
        message-path: benchmark.txt 
        message-id: benchmark
      
    - name: Cleanup
      run: |
          ./.github/workflows/gcloud_ssh.sh " rm -r -f $BRANCH_NAME"

      
