name: JMH Benchmark

on:
  pull_request:


jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v1
      id: comment-branch


    - name: Set branch name
      run: echo "BRANCH_NAME=${{ steps.comment-branch.outputs.head_ref }}" >> $GITHUB_ENV
    
    - id: 'auth'
      name: Authenticating
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
        
    - name: Check gcloud version and authentication
      run: |
        gcloud version
        gcloud auth list
    
    - name: Copy exported text file from Google Cloud Compute Engine
      run: |
        gcloud compute scp root@instance-1:hi/1.txt ./exported_text.txt --zone us-central1-a
   
    - name: Comment 2
      uses: mshick/add-pr-comment@v2
      if: always()
      with: 
        message: Main Benchmark
        
        
        message-path: exported_text.txt

    - name: Run JMH benchmarks on Compute Engine
      run: |
        gcloud compute ssh \
          --project=nullway-jmh \
          --zone=us-central1-a \
          root@instance-1 \
          --command=" export BRANCH_NAME=${BRANCH_NAME} && echo $BRANCH_NAME && git clone --branch $BRANCH_NAME --single-branch git@github.com:armughan11/NullAway.git && cd NullAway/ && ./gradlew jmh "
