name: Run JMH Benchmarks for Pull Request 

on:
  issue_comment:
    types: [created]


jobs:
  setup:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/benchmark') 
    runs-on: ubuntu-latest
    permissions: write-all
  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get PR branch
      uses: xt0rted/pull-request-comment-branch@v1
      id: comment-branch


    - name: Set branch name
      run: echo "BRANCH_NAME=${{ steps.comment-branch.outputs.head_ref }}" >> $GITHUB_ENV

    
    - id: 'auth'
      name: Authenticating
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
      
    - name: Run benchmarks and cleanup
      run: |
          gcloud compute scp ./.github/workflows/run_benchmarks.sh root@instance-1:/tmp --zone=us-central1-a
          gcloud compute ssh \
            --project=nullway-jmh \
            --zone=us-central1-a \
            root@instance-1 \
            --command="bash /tmp/run_benchmarks.sh ${BRANCH_NAME}"

      
