name: JMH Benchmark

on:
  pull_request:


jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - id: 'auth'
      name: Authenticating
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
        
    - name: Check gcloud version and authentication
      run: |
        gcloud version
        gcloud auth list
    
    - name: Start SSH agent
      run: |
        eval "$(ssh-agent -s)"
        echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> $GITHUB_ENV
        
    - name: Add SSH key to the agent
      run: |
        echo "${{ secrets.GH_KEY }}" > private_key
        chmod 600 private_key
        ssh-add private_key
        rm private_key
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    - name: Run JMH benchmarks on Compute Engine
      run: |
        gcloud compute ssh instance-1 \
          --zone=us-central1-a \
          --command=" git clone git@github.com:armughan11/NullAway.git && cd NullAway/ && ./gradlew jmh"
