name: JMH Benchmark

on:
  pull_request:


jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - id: 'auth'
      name: Authenticating
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
        
    - name: Check gcloud version and authentication
      run: |
        gcloud version
        gcloud auth list
    
    - name: Run JMH benchmarks on Compute Engine
      run: |
        gcloud compute ssh \
          --project=nullway-jmh \
          --zone=us-central1-a \
          root@instance-1 \
          --command=" git clone git@github.com:armughan11/NullAway.git && cd NullAway/ && ./gradlew jmh "
